# -*- coding: UTF-8 -*-
#!/usr/bin/env python

__author__ = "Kurt Pagani <pagani@scios.ch>"
__svn_id__ = "$Id:$"
__rev_id__ = "Rev. 29.05.2012 02:58:59"

usage = """YAML to Python converter (using PyYAML)
Usage: python yaml2.py filename.yaml  (prints on stdout) """

import yaml
import sys



def main():
  args = sys.argv
  argc = len(args)

  if argc <= 1:
    print usage
    sys.exit(1)

  print "# Generated by yaml2py from file: {} \n".format(args[1])
  print "data = {}".format(list(yaml.load_all(open(args[1]).read())))


if __name__ == '__main__':
  main()


# Ex.
# python yaml2.py org.yaml > y.py
# Run y.py in SciOS PyShell (leftmost toolbar button)
# len(data) -> 1
# y = data[0]
# y.keys() -> ['YAML Resources', 'YAML', 'Related Projects', 'Projects', ...]
# y['YAML'] -> "YAML Ain't Markup Language"
# ...
#